name: Testing

on:
  pull_request:
  push:
    branches: [main]

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Python environment report
        run: python -c "import sys; print(sys.version)"
      - name: Run py-dependency-install test
        uses: py-actions/py-dependency-install@master
